import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from './layout.module.css';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className={styles.header}>
        <Link href="/">
          <Image src={'/images/logo.png'} width={50} height={50} alt="logo" />
        </Link>
        <nav className={styles.nav}>
          <Link href="/about">About</Link>

          <Link href="/posts">Posts</Link>
        </nav>
      </header>
      <main>{children}</main>
    </>
  );
}
